config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  resources :links do
    collection do
      post :import
      get  :coord
    end
  end
  resources :nodes do
    collection do
      post :import
      get  :coord
    end
  end
  get 'map' => 'nodes#map'

end

app/models/link.rb
class Link < ActiveRecord::Base
  has_many :link_nodes, primary_key: :link_id, foreign_key: :link_id
  has_many :node, through: :link_nodes

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      link = find_by(link_id: row["link_id"]) || new
      names_to_use = attribute_names.select { |name| !name.in? ["id", "created_at", "updated_at"] }
      attributes_to_use = names_to_use.map do |name|
        if name =~ /latitude|longitude/ && row[name]
          lats_or_lngs = row[name].split(".", 3).map(&:to_f)
          puts lats_or_lngs
          floatized = lats_or_lngs[0] + (lats_or_lngs[1] / 60) + (lats_or_lngs[2] / 60 / 60)
          [name, floatized]
        else
          [name, row[name]]
        end
      end.to_h
      puts attributes_to_use
      link.update_attributes(attributes_to_use)
      link.save!
      ln1 = LinkNode.find_or_initialize_by(link_id: link.link_id, node_id: link.src_node_id)
      ln1.save!
      ln2 = LinkNode.find_or_initialize_by(link_id: link.link_id, node_id: link.dst_node_id)
      ln2.save!
    end
  end
end

app/models/link_node.rb
class LinkNode < ActiveRecord::Base
  belongs_to :link, primary_key: :link_id, foreign_key: :link_id, dependent: :destroy
  belongs_to :node, primary_key: :node_id, foreign_key: :node_id, dependent: :destroy
end

app/models/node.rb
class Node < ActiveRecord::Base
  has_many :link_nodes, primary_key: :node_id, foreign_key: :node_id
  has_many :links, through: :link_nodes

  reverse_geocoded_by :latitude, :longitude
  after_validation :reverse_geocode

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      node = find_by(node_id: row["node_id"]) || new
      names_to_use = attribute_names.select { |name| !name.in? ["id", "created_at", "updated_at"] }
      attributes_to_use = names_to_use.map do |name|
        if name =~ /latitude|longitude/ && row[name]
          lats_or_lngs = row[name].split(".", 3).map(&:to_f)
          floatized = lats_or_lngs[0] + (lats_or_lngs[1] / 60) + (lats_or_lngs[2] / 60 / 60)
          [name, floatized]
        else
          [name, row[name]]
        end
      end.to_h
      puts attributes_to_use
      node.update_attributes(attributes_to_use)
      node.save!
      (1..5).each do |n|
        l = node.send "link_#{n}"
        ln = LinkNode.find_or_initialize_by(link_id: l, node_id: node.node_id)
        ln.save!
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show, :edit, :update, :destroy]

  SEARCH_RADIUS_IN_KM = 0.100

  def coord
    nearby_nodes = Node.includes(:links).near([coord_params[:lat], coord_params[:lng]], SEARCH_RADIUS_IN_KM, units: :km)
    @links ||= []
    nearby_nodes.each do |node|
      @links = @links | node.links
    end
    render :index
  end

  def import
    Link.import(params[:file])
    redirect_to links_path, notice: "Import success!"
  end

  # GET /links
  # GET /links.json
  def index
    @links = Link.includes(:node).all
  end

  # GET /links/1
  # GET /links/1.json
  def show
  end

  # GET /links/new
  def new
    @link = Link.new
  end

  # GET /links/1/edit
  def edit
  end

  # POST /links
  # POST /links.json
  def create
    @link = Link.new(link_params)

    respond_to do |format|
      if @link.save
        format.html { redirect_to @link, notice: 'Link was successfully created.' }
        format.json { render :show, status: :created, location: @link }
      else
        format.html { render :new }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /links/1
  # PATCH/PUT /links/1.json
  def update
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to @link, notice: 'Link was successfully updated.' }
        format.json { render :show, status: :ok, location: @link }
      else
        format.html { render :edit }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  # DELETE /links/1.json
  def destroy
    @link.destroy
    respond_to do |format|
      format.html { redirect_to links_url, notice: 'Link was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @link = Link.includes(:node).find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def link_params
      params.require(:link).permit(:link_id, :src_node_id, :dst_node_id, :link_type, :width, :hill, :gap, :gap_latitude, :gap_longitude, :steps, :bus_stop, :bus_stop_latitude, :bus_stop_longitude, :blind_guide, :signals, :street_name, :length)
    end

    def coord_params
      params.permit(:lat, :lng)
    end
end

app/controllers/nodes_controller.rb
class NodesController < ApplicationController
  before_action :set_node, only: [:show, :edit, :update, :destroy]

  SEARCH_RADIUS_IN_KM = 0.100

  def coord
    @nodes = Node.includes(:links).near([coord_params[:lat], coord_params[:lng]], SEARCH_RADIUS_IN_KM, units: :km)
    render :index
  end

  def import
    Node.import(params[:file])
    redirect_to nodes_path, notice: "Import success!"
  end

  # GET /nodes
  # GET /nodes.json
  def index
    @nodes = Node.includes(:links).all
  end

  # GET /nodes/map
  def map
    render :map
  end

  # GET /nodes/1
  # GET /nodes/1.json
  def show
  end

  # GET /nodes/new
  def new
    @node = Node.new
  end

  # GET /nodes/1/edit
  def edit
  end

  # POST /nodes
  # POST /nodes.json
  def create
    @node = Node.new(node_params)

    respond_to do |format|
      if @node.save
        format.html { redirect_to @node, notice: 'Node was successfully created.' }
        format.json { render :show, status: :created, location: @node }
      else
        format.html { render :new }
        format.json { render json: @node.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nodes/1
  # PATCH/PUT /nodes/1.json
  def update
    respond_to do |format|
      if @node.update(node_params)
        format.html { redirect_to @node, notice: 'Node was successfully updated.' }
        format.json { render :show, status: :ok, location: @node }
      else
        format.html { render :edit }
        format.json { render json: @node.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nodes/1
  # DELETE /nodes/1.json
  def destroy
    @node.destroy
    respond_to do |format|
      format.html { redirect_to nodes_url, notice: 'Node was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_node
      @node = Node.includes(:links).find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def node_params
      params.require(:node).permit(:node_id, :latitude, :longitude)
    end

    def coord_params
      params.permit(:lat, :lng)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/nodes_helper.rb
module NodesHelper
end

app/views/home/index.html.slim
.row
  .col-md-6
    .jumbotron
      .innertron
        h1
          | hokoo
        p
          | 歩行空間ネットワークデータ・プラットフォーム
        p
          => link_to "リンクデータ", links_path, class: "btn btn-primary"
          = link_to "ノードデータ", nodes_path, class: "btn btn-primary"
.row
  .col-md-7
    .panel.panel-default
      .panel-heading
        | API Specs
      .panel-body
        ul
          li Basic RESTful APIs with CRUD operation
          li
            | CSV import feature: 
            => link_to "Links", links_path
            = link_to "Nodes", nodes_path
          li
            | Coordinate queries:
            pre GET /links/coord(.json)?lat=[Latitude in float]&lng=[longitude in float]
            pre GET /nodes/coord(.json)?lat=[Latitude in float]&lng=[longitude in float]

app/views/layouts/application.html.slim
doctype html
html[lang="en"]
  head
    meta[charset="utf-8"]
    meta[http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"]
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : "hokoo"
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"
  body class=(controller.controller_name == "home" ? "home" : "")
    .navbar.navbar-default.navbar-static-top
      a[href="https://github.com/YusukeKanai/Hackathon_TeamMakuhari", target="_blank"]
        img[style="position: absolute; top: 0; right: 0; border: 0;" src="https://camo.githubusercontent.com/e7bbb0521b397edbd5fe43e7f760759336b5e05f/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f6769746875622f726962626f6e732f666f726b6d655f72696768745f677265656e5f3030373230302e706e67" alt="Fork me on GitHub" data-canonical-src="https://s3.amazonaws.com/github/ribbons/forkme_right_green_007200.png"]
      .container
        button.navbar-toggle[type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse"]
          span.icon-bar
          span.icon-bar
          span.icon-bar
        a.navbar-brand[href="/"]
          | hokoo
        .navbar-collapse.collapse.navbar-responsive-collapse
          ul.nav.navbar-nav
            li
              = link_to "Links", "/links"
            li
              = link_to "Nodes", "/nodes"
    .container
      .row
        .col-md-12
          = bootstrap_flash
          = yield
      footer
        p
          | © Company 2015

app/views/links/_form.html.slim
= form_for @link, :html => { :class => "form-horizontal link" } do |f|
  - if @link.errors.any?
    #error_expl.panel.panel-danger
      .panel-heading
        h3.panel-title
          = pluralize(@link.errors.count, "error")
          |  prohibited this link from being saved:
      .panel-body
        ul
          - @link.errors.full_messages.each do |msg|
            li
              = msg
  .control-group
    = f.label :id, :class => 'control-label'
    .controls
      = f.text_field :id, :class => 'form-control'
    = error_span(@link[:id])
  .control-group
    = f.label :src_node_id, :class => 'control-label'
    .controls
      = f.text_field :src_node_id, :class => 'form-control'
    = error_span(@link[:src_node_id])
  .control-group
    = f.label :dst_node_id, :class => 'control-label'
    .controls
      = f.text_field :dst_node_id, :class => 'form-control'
    = error_span(@link[:dst_node_id])
  .control-group
    = f.label :link_type, :class => 'control-label'
    .controls
      = f.text_field :link_type, :class => 'form-control'
    = error_span(@link[:link_type])
  .control-group
    = f.label :width, :class => 'control-label'
    .controls
      = f.text_field :width, :class => 'form-control'
    = error_span(@link[:width])
  .control-group
    = f.label :hill, :class => 'control-label'
    .controls
      = f.text_field :hill, :class => 'form-control'
    = error_span(@link[:hill])
  .control-group
    = f.label :gap, :class => 'control-label'
    .controls
      = f.text_field :gap, :class => 'form-control'
    = error_span(@link[:gap])
  .control-group
    = f.label :gap_latitude, :class => 'control-label'
    .controls
      = f.text_field :gap_latitude, :class => 'form-control'
    = error_span(@link[:gap_latitude])
  .control-group
    = f.label :gap_longitude, :class => 'control-label'
    .controls
      = f.text_field :gap_longitude, :class => 'form-control'
    = error_span(@link[:gap_longitude])
  .control-group
    = f.label :steps, :class => 'control-label'
    .controls
      = f.text_field :steps, :class => 'form-control'
    = error_span(@link[:steps])
  .control-group
    = f.label :bus_stop, :class => 'control-label'
    .controls
      = f.text_field :bus_stop, :class => 'form-control'
    = error_span(@link[:bus_stop])
  .control-group
    = f.label :bus_stop_latitude, :class => 'control-label'
    .controls
      = f.text_field :bus_stop_latitude, :class => 'form-control'
    = error_span(@link[:bus_stop_latitude])
  .control-group
    = f.label :bus_stop_longitude, :class => 'control-label'
    .controls
      = f.text_field :bus_stop_longitude, :class => 'form-control'
    = error_span(@link[:bus_stop_longitude])
  .control-group
    = f.label :blind_guide, :class => 'control-label'
    .controls
      = f.text_field :blind_guide, :class => 'form-control'
    = error_span(@link[:blind_guide])
  .control-group
    = f.label :signals, :class => 'control-label'
    .controls
      = f.text_field :signals, :class => 'form-control'
    = error_span(@link[:signals])
  .control-group
    = f.label :street_name, :class => 'control-label'
    .controls
      = f.text_field :street_name, :class => 'form-control'
    = error_span(@link[:street_name])
  .control-group
    = f.label :length, :class => 'control-label'
    .controls
      = f.text_field :length, :class => 'form-control'
    = error_span(@link[:length])
  = f.submit nil, :class => 'btn btn-primary'
  = link_to t('.cancel', :default => t("helpers.links.cancel")),
                links_path, :class => 'btn btn-default'

app/views/links/edit.html.slim
- model_class = Link
.page-header
  h1
    =t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => 'form'

app/views/links/index.html.slim
- model_class = Link
.page-header
  h1
    =t '.title', :default => model_class.model_name.human.pluralize.titleize
.row
  .col-md-12
    .pull-right
      = link_to t('.new', :default => t("helpers.links.new")),
                          new_link_path,
                          :class => 'btn btn-primary'
    = form_tag import_links_path, multipart: true do
      = file_field_tag :file
      = submit_tag "Import", class: "btn btn-info"
.row
  .col-md-12.long-table
    table.table.table-striped
      thead
        tr
          th
            =t '.actions', :default => t("helpers.actions")
          th
            = model_class.human_attribute_name(:link_id)
          th
            = model_class.human_attribute_name(:node_id)
          th
            = model_class.human_attribute_name(:link_type)
          th
            = model_class.human_attribute_name(:width)
          th
            = model_class.human_attribute_name(:hill)
          th
            = model_class.human_attribute_name(:gap)
          th
            = model_class.human_attribute_name(:gap_latitude)
          th
            = model_class.human_attribute_name(:gap_longitude)
          th
            = model_class.human_attribute_name(:steps)
          th
            = model_class.human_attribute_name(:bus_stop)
          th
            = model_class.human_attribute_name(:bus_stop_latitude)
          th
            = model_class.human_attribute_name(:bus_stop_longitude)
          th
            = model_class.human_attribute_name(:blind_guide)
          th
            = model_class.human_attribute_name(:signals)
          th
            = model_class.human_attribute_name(:street_name)
          th
            = model_class.human_attribute_name(:length)
          th
            = model_class.human_attribute_name(:created_at)
      tbody
        - @links.each do |link|
          tr
            td
              = link_to t('.edit', :default => t("helpers.links.edit")),
                                       edit_link_path(link), :class => 'btn btn-default btn-xs'
              = link_to t('.destroy', :default => t("helpers.links.destroy")),
                                       link_path(link),
                                       :method => :delete,
                                       :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                                       :class => 'btn btn-xs btn-danger'
            td
              = link_to link.link_id, link
            td
              - link.node.each do |node|
                = link_to node.node_id, node
                br
            td
              = link.link_type
            td
              = link.width
            td
              = link.hill
            td
              = link.gap
            td
              = link.gap_latitude
            td
              = link.gap_longitude
            td
              = link.steps
            td
              = link.bus_stop
            td
              = link.bus_stop_latitude
            td
              = link.bus_stop_longitude
            td
              = link.blind_guide
            td
              = link.signals
            td
              = link.street_name
            td
              = link.length
            td
              =l link.created_at

app/views/links/new.html.slim
- - model_class = Link
.page-header
  h1
    =t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => 'form'

app/views/links/show.html.slim
- model_class = Link
.page-header
  h1
    =t '.title', :default => model_class.model_name.human.titleize
dl.dl-horizontal
  dt
    strong
      = model_class.human_attribute_name(:id)
      | :
  dd
    = @link.id
  dt
    strong
      = model_class.human_attribute_name(:link_id)
      | :
  dd
    = @link.link_id
  dt
    strong
      = model_class.human_attribute_name(:node_id)
      | :
  dd
    - @link.node.each do |node|
      = link_to node.node_id, node
      br
  dt
    strong
      = model_class.human_attribute_name(:link_type)
      | :
  dd
    = @link.link_type
  dt
    strong
      = model_class.human_attribute_name(:width)
      | :
  dd
    = @link.width
  dt
    strong
      = model_class.human_attribute_name(:hill)
      | :
  dd
    = @link.hill
  dt
    strong
      = model_class.human_attribute_name(:gap)
      | :
  dd
    = @link.gap
  dt
    strong
      = model_class.human_attribute_name(:gap_latitude)
      | :
  dd
    = @link.gap_latitude
  dt
    strong
      = model_class.human_attribute_name(:gap_longitude)
      | :
  dd
    = @link.gap_longitude
  dt
    strong
      = model_class.human_attribute_name(:steps)
      | :
  dd
    = @link.steps
  dt
    strong
      = model_class.human_attribute_name(:bus_stop)
      | :
  dd
    = @link.bus_stop
  dt
    strong
      = model_class.human_attribute_name(:bus_stop_latitude)
      | :
  dd
    = @link.bus_stop_latitude
  dt
    strong
      = model_class.human_attribute_name(:bus_stop_longitude)
      | :
  dd
    = @link.bus_stop_longitude
  dt
    strong
      = model_class.human_attribute_name(:blind_guide)
      | :
  dd
    = @link.blind_guide
  dt
    strong
      = model_class.human_attribute_name(:signals)
      | :
  dd
    = @link.signals
  dt
    strong
      = model_class.human_attribute_name(:street_name)
      | :
  dd
    = @link.street_name
  dt
    strong
      = model_class.human_attribute_name(:length)
      | :
  dd
    = @link.length
= link_to t('.back', :default => t("helpers.links.back")),
                links_path, :class => 'btn btn-default'
= link_to t('.edit', :default => t("helpers.links.edit")),
                edit_link_path(@link), :class => 'btn btn-default'
= link_to t('.destroy', :default => t("helpers.links.destroy")),
                link_path(@link),
                :method => 'delete',
                :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                :class => 'btn btn-danger'

app/views/nodes/_form.html.slim
= form_for @node, :html => { :class => "form-horizontal node" } do |f|
  - if @node.errors.any?
    #error_expl.panel.panel-danger
      .panel-heading
        h3.panel-title
          = pluralize(@node.errors.count, "error")
          |  prohibited this node from being saved:
      .panel-body
        ul
          - @node.errors.full_messages.each do |msg|
            li
              = msg
  .control-group
    = f.label :node_id, :class => 'control-label'
    .controls
      = f.text_field :node_id, :class => 'form-control'
    = error_span(@node[:node_id])
  .control-group
    = f.label :latitude, :class => 'control-label'
    .controls
      = f.text_field :latitude, :class => 'form-control'
    = error_span(@node[:latitude])
  .control-group
    = f.label :longitude, :class => 'control-label'
    .controls
      = f.text_field :longitude, :class => 'form-control'
    = error_span(@node[:longitude])
  .control-group
    = f.label :link_1, :class => 'control-label'
    .controls
      = f.text_field :link_1, :class => 'form-control'
    = error_span(@node[:link_1])
  .control-group
    = f.label :link_2, :class => 'control-label'
    .controls
      = f.text_field :link_2, :class => 'form-control'
    = error_span(@node[:link_2])
  .control-group
    = f.label :link_3, :class => 'control-label'
    .controls
      = f.text_field :link_3, :class => 'form-control'
    = error_span(@node[:link_3])
  .control-group
    = f.label :link_4, :class => 'control-label'
    .controls
      = f.text_field :link_4, :class => 'form-control'
    = error_span(@node[:link_4])
  .control-group
    = f.label :link_5, :class => 'control-label'
    .controls
      = f.text_field :link_5, :class => 'form-control'
    = error_span(@node[:link_5])
  = f.submit nil, :class => 'btn btn-primary'
  = link_to t('.cancel', :default => t("helpers.links.cancel")),
                nodes_path, :class => 'btn btn-default'

app/views/nodes/edit.html.slim
- model_class = Node
.page-header
  h1
    =t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => 'form'

app/views/nodes/index.html.slim
- model_class = Node
.page-header
  h1
    =t '.title', :default => model_class.model_name.human.pluralize.titleize
.row
  .col-md-12
    .pull-right
      = link_to t('.new', :default => t("helpers.links.new")),
                          new_node_path,
                          :class => 'btn btn-primary'
    = form_tag import_nodes_path, multipart: true do
      = file_field_tag :file
      = submit_tag "Import", class: "btn btn-info"
.row
  .col-md-12.long-table
    table.table.table-striped
      thead
        tr
          th
            =t '.actions', :default => t("helpers.actions")
          th
            = model_class.human_attribute_name(:node_id)
          th
            = model_class.human_attribute_name(:latitude)
          th
            = model_class.human_attribute_name(:longitude)
          th
            = model_class.human_attribute_name(:link)
          th
            = model_class.human_attribute_name(:created_at)
      tbody
        - @nodes.each do |node|
          tr
            td
              = link_to t('.edit', :default => t("helpers.links.edit")),
                                      edit_node_path(node), :class => 'btn btn-default btn-xs'
              = link_to t('.destroy', :default => t("helpers.links.destroy")),
                                      node_path(node),
                                      :method => :delete,
                                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                                      :class => 'btn btn-xs btn-danger'
            td
              = link_to node.node_id, node
            td
              = node.latitude
            td
              = node.longitude
            td
              - node.links.each do |link|
                = link_to link.link_id, link
                br
            td
              =l node.created_at

app/views/nodes/map.html.slim
= javascript_include_tag 'https://maps.google.com/maps/api/js?key=AIzaSyCLLo-0xVeu_vHKJSdblqS2hIUN3xccP0I'
#map

app/views/nodes/new.html.slim
- model_class = Node
.page-header
  h1
    =t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => 'form'

app/views/nodes/show.html.slim
- model_class = Node
.page-header
  h1
    =t '.title', :default => model_class.model_name.human.titleize
dl.dl-horizontal
  dt
    strong
      = model_class.human_attribute_name(:node_id)
      | :
  dd
    = @node.node_id
  dt
    strong
      = model_class.human_attribute_name(:latitude)
      | :
  dd
    = @node.latitude
  dt
    strong
      = model_class.human_attribute_name(:longitude)
      | :
  dd
    = @node.longitude
  dt
    strong
      = model_class.human_attribute_name(:link)
      | :
  dd
    - @node.links.each do |link|
      = link_to link.link_id, link
      br
= link_to t('.back', :default => t("helpers.links.back")),
                nodes_path, :class => 'btn btn-default'
= link_to t('.edit', :default => t("helpers.links.edit")),
                edit_node_path(@node), :class => 'btn btn-default'
= link_to t('.destroy', :default => t("helpers.links.destroy")),
                node_path(@node),
                :method => 'delete',
                :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                :class => 'btn btn-danger'